version: '3'
services:
    ldap:
        image: osixia/openldap:1.4.0
        restart: always
        domainname: "example.com"
        hostname: "ldap"
        command: --copy-service
        ports:
            - 389:389
            - 636:636
        volumes:
            - ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
        environment:
            LDAP_ORGANISATION: "Example Corp"
            LDAP_DOMAIN: "example.com"
            LDAP_ADMIN_PASSWORD: "changeMe-Pl34$e"
            LDAP_READONLY_USER: "true"
            LDAP_READONLY_USER_USERNAME: "butler"
            LDAP_READONLY_USER_PASSWORD: "readonly"

    webserver:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../oauth:/var/www/html/oauth
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    php:
        build: ../Docker/php-ldap-pgsql
        image: php-ldap-pgsql
        volumes:
            - ../oauth:/var/www/html/oauth
        environment:
            ldap_host: ldap://ldap:389/
            ldap_port: 389
            ldap_version: 3
            ldap_search_attribute: uid
            ldap_base_dn: "dc=example,dc=com"
            ldap_filter: "(objectClass=*)"
            ldap_bind_dn: "cn=butler,dc=example,dc=com"
            ldap_bind_pass: "readonly"
            ldap_secure: 0
            ldap_cert_path: "/var/www/html/oauth/certs/cert.crt"
            ldap_key_path: "/var/www/html/oauth/certs/private.key"
            db_host: "database"
            db_port: "5432"
            db_type: "pgsql"
            db_name: "oauth_db"
            db_user: "oauth"
            db_pass: "oauth_secure-pass"
        depends_on:
            - database
            - ldap

    database:
        image: postgres:alpine
        restart: always
        volumes:
            - ../db_init/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
            - ../db_init/config_init.sh.example:/docker-entrypoint-initdb.d/config_init.sh
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: rootroot
            POSTGRES_HOST_AUTH_METHOD: trust
            client_id: 123456789abcdef123456789abcdef
            client_secret: fedcba987654321fedcba987654321
            redirect_uri: "http://localhost/signup/gitlab/complete"
            grant_types: "authorization_code"
            scope: "api"
            user_id: ""
            db_user: "oauth"
            db_pass: "oauth_secure-pass"
            db_name: "oauth_db"
            db_host: "127.0.0.1"
            db_port: "5432"

    mattermost:
        image: mattermost/mattermost-preview
        ports:
            - 8065:8065
        extra_hosts:
            - dockerhost:127.0.0.1
        volumes:
            - ./config.json:/mm/mattermost/config/config_docker.json
